In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
url = 'https://www.ssbwiki.com/Top_100_Melee_Players_of_All_Time'

data = requests.get(url)

soup = BeautifulSoup(data.text, 'html.parser')

In [5]:
new_soup = soup.find(class_ = 'wikitable')

In [6]:
tbody = new_soup.find('tbody')

In [7]:
df = pd.DataFrame(columns = ['rank','player','empty1','empty2','empty3'])

In [8]:
for row in tbody.find_all('tr'):
    columns = row.find_all('td')
    
    if (columns != []):
        rank = columns[0].text.strip()
        player = columns[1].text.strip()
        empty1 = columns[2].text.strip()
        empty2 = columns[3].text.strip()
        empty3 = columns[4].text.strip()
        
        df = df.append({'rank': rank, 'player': player, 'empty1': empty1, 'empty2': empty2, 'empty3': empty3}, ignore_index = True)

In [9]:
df.head()

  rank     player empty1 empty2 empty3
0    1      Mango      —      —
1    2     Armada      —      —
2    3  Hungrybox      —      —
3    4        Ken      —      —
4    5   Mew2King      —      —

In [10]:
#or

In [11]:
df2 = pd.DataFrame(columns = ['rank','player'])

for row in tbody.find_all('tr'):
    columns = row.find_all('td')
    
    if (columns != []):
        rank = columns[0].text.strip()
        player = columns[1].text.strip()
        
        df2 = df2.append({'rank': rank, 'player': player}, ignore_index = True)

In [12]:
df2.head()

  rank     player
0    1      Mango
1    2     Armada
2    3  Hungrybox
3    4        Ken
4    5   Mew2King

In [18]:
df3 = pd.DataFrame(columns = ['main'])
for tr in tbody.find_all('tr'):
    for td in tbody.find_all('td'):
        character = td.find_all('a')
        
        if (character != []):
            main = character[0]['title']
            
            df3 = df3.append({'main':main}, ignore_index = True)

In [16]:
df3

               main
0               USA
1        Fox (SSBM)
2            Sweden
3      Peach (SSBM)
4               USA
...             ...
20195  Marth (SSBM)
20196           USA
20197  Marth (SSBM)
20198           USA
20199    Fox (SSBM)

[20200 rows x 1 columns]