In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [3]:
url = 'https://www.ssbwiki.com/Top_100_Melee_Players_of_All_Time'

data = requests.get(url)

soup = BeautifulSoup(data.text, 'html.parser')

In [12]:
tbody = soup.select('table')[1].find('tbody')

In [13]:
df = pd.DataFrame(columns = ['rank','player','empty1','empty2','empty3'])

In [14]:
for row in tbody.find_all('tr'):
    columns = row.find_all('td')
    
    if (columns != []):
        rank = columns[0].text.strip()
        player = columns[1].text.strip()
        empty1 = columns[2].text.strip()
        empty2 = columns[3].text.strip()
        empty3 = columns[4].text.strip()
        
        df = df.append({'rank': rank, 'player': player, 'empty1': empty1, 'empty2': empty2, 'empty3': empty3}, ignore_index = True)

In [15]:
df.head()

  rank     player empty1 empty2 empty3
0    1      Mango      —      —
1    2     Armada      —      —
2    3  Hungrybox      —      —
3    4        Ken      —      —
4    5   Mew2King      —      —

In [16]:
df2 = pd.DataFrame(columns = ['rank','player'])

for row in tbody.find_all('tr'):
    columns = row.find_all('td')
    
    if (columns != []):
        rank = columns[0].text.strip()
        player = columns[1].text.strip()
        
        df2 = df2.append({'rank': rank, 'player': player}, ignore_index = True)

In [17]:
df2.head()

  rank     player
0    1      Mango
1    2     Armada
2    3  Hungrybox
3    4        Ken
4    5   Mew2King

In [18]:
df3 = pd.DataFrame(columns = ['main', 'href'])
for tr in tbody.find_all('tr'):
    for td in tbody.find_all('td'):
        character = td.find_all('a')
        
        if (character != []):
            main = character[0]['title']
            href = character[0]['href']
            
            df3 = df3.append({'main':main, 'href': href}, ignore_index = True)

In [22]:
df3.head(20)

                 main                                 href
0                 USA  /File:Flag_of_the_United_States.svg
1          Fox (SSBM)                          /Fox_(SSBM)
2              Sweden             /File:Flag_of_Sweden.svg
3        Peach (SSBM)                        /Peach_(SSBM)
4                 USA  /File:Flag_of_the_United_States.svg
5   Jigglypuff (SSBM)                   /Jigglypuff_(SSBM)
6                 USA  /File:Flag_of_the_United_States.svg
7        Marth (SSBM)                        /Marth_(SSBM)
8                 USA  /File:Flag_of_the_United_States.svg
9        Marth (SSBM)                        /Marth_(SSBM)
10             Sweden             /File:Flag_of_Sweden.svg
11         Fox (SSBM)                          /Fox_(SSBM)
12                USA  /File:Flag_of_the_United_States.svg
13       Falco (SSBM)                        /Falco_(SSBM)
14                USA  /File:Flag_of_the_United_States.svg
15       Marth (SSBM)                        /Marth_(SSBM)
16                USA  /File:Flag_of_the_United_States.svg
17       Marth (SSBM)                        /Marth_(SSBM)
18                USA  /File:Flag_of_the_United_States.svg
19       Sheik (SSBM)                        /Sheik_(SSBM)